name: 🐧 Linux Smoke Tests

on:
  workflow_call:
  workflow_dispatch:
  push:

jobs:
  linux_smoke_tests:
    name: "linux smoke tests workflow"
    runs-on: ubuntu-latest
    steps:
      - name: "Install llvm@18 dependency"
        run:
          sudo apt install -y llvm-18
      - name: "Install pip dependency"
        run: pip install lit
      - uses: "actions/checkout@v3"
        with:
          fetch-depth: 0
      - name: "Cache project build directory"
        uses: actions/cache@v4
        env:
          cache-name: cache-cmake-dependency-builds
        with:
          path: |
            ${{github.workspace}}/build/
            ${{github.workspace}}/build/
          key: ${{ env.cache-name }}-${{ matrix.os }}-${{ matrix.cxx }}-${{ hashFiles('**/CMakeLists.txt', 'cmake/**') }}
          restore-keys: |
            ${{ env.cache-name }}-${{ matrix.os }}-${{ matrix.cxx }}-

      - name: "Configure the project"
        run: "cmake -Bbuild -DCMAKE_BUILD_TYPE=RelWithDebInfo -DLLVM_ENABLE_ASSERTIONS=1"

      - name: "Run unit tests"
        run: |
          source /home/ubuntu/myenv/bin/activate
          ./coverage.sh
