name: 🐧 Linux Smoke Tests

on:
  workflow_call:
  workflow_dispatch:
  push:

jobs:
  linux_smoke_tests:
    name: "linux smoke tests workflow"
    runs-on: ubuntu-latest
    steps:
      - name: "Install llvm@18 dependency"
        run:
          sudo apt install -y llvm-18
      - name: "Install pip dependency"
        run:
          pip install lit
      - name: "Install Flex (and Bison)"
        run: sudo apt install -y flex bison
      - uses: "actions/checkout@v3"
        with:
          fetch-depth: 0
      - name: "Cache project build directory"
        uses: actions/cache@v4
        env:
          cache-name: cache-cmake-dependency-builds
        with:
          path: |
            ${{github.workspace}}/build/
            ${{github.workspace}}/build/
          key: ${{ env.cache-name }}-${{ matrix.os }}-${{ matrix.cxx }}-${{ hashFiles('**/CMakeLists.txt', 'cmake/**') }}
          restore-keys: |
            ${{ env.cache-name }}-${{ matrix.os }}-${{ matrix.cxx }}-

      - name: "Configure the project"
        run: |
          export LLVM_VERSION=$(ls /usr/lib/llvm-18 | head -n 1)
          export LLVM_DIR="/usr/lib/llvm-18/cmake"
          export PATH="/usr/lib/llvm-18/bin:$PATH"
          export BISON_EXECUTABLE=$(which bison)
          export FLEX_INCLUDE_DIR=$(dirname $(find /usr/include -name FlexLexer.h | head -n 1))
          cmake -B build -DCMAKE_BUILD_TYPE=RelWithDebInfo \
            -DLLVM_DIR=$LLVM_DIR \
            -DBISON_EXECUTABLE=$BISON_EXECUTABLE \
            -DLLVM_ENABLE_ASSERTIONS=1 \
            -DCMAKE_CXX_FLAGS="-I$FLEX_INCLUDE_DIR"

      - name: "Run unit tests"
        run:
          ./coverage.sh
