name: 🧹 Lint the codebase

on:
  workflow_call:
  push:

jobs:
  run_clang-format:
    name: Lint the codebase with clang-format
    runs-on: macos-latest
    strategy:
      matrix:
        path:
          - 'lib'
          - 'include'
          - 'tools'
    steps:
    - uses: actions/checkout@v4
    - name: Run clang-format style check for C/C++/ programs
      uses: jidicula/clang-format-action@v4.13.0
      with:
        clang-format-version: '19'
        check-path: ${{ matrix.path }}
